version: "3.8"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.6.0
    container_name: rest-proxy
    depends_on:
      - kafka
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082

  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: sanjeevani
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  consumer:
    build: .
    container_name: blood-consumer
    command: node blood_consumer.js
    depends_on:
      - rest-proxy
      - mongo
    environment:
      REST_PROXY: http://rest-proxy:8082
      MONGO_URI: mongodb://mongo:27017/sanjeevani
      MONGO_DB: sanjeevani
      MONGO_COLLECTION: blood_records
    ports:
      - "3001:3000"

  notification_producer:
    build: .
    container_name: notification-producer
    command: node notification_producer.js
    depends_on:
      - rest-proxy
    environment:
      REST_PROXY: http://rest-proxy:8082
      TOPIC: notifications
      PORT: 3000
    ports:
      - "3000:3000"

  notification_consumer:
    build: .
    container_name: notification-consumer
    command: node notification_consumer.js
    depends_on:
      - rest-proxy
    environment:
      REST_PROXY: http://rest-proxy:8082
      PORT: 4000
    ports:
      - "4000:4000"
    restart: on-failure

volumes:
  mongo-data:
